const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("Preparing deployment...");

  // Get the ContractFactory for TrustRegistry
  const TrustRegistry = await hre.ethers.getContractFactory("TrustRegistry");

  // Deploy the contract
  const trustRegistry = await TrustRegistry.deploy();

  // Wait for the deployment to finish
  await trustRegistry.waitForDeployment();

  const deployedAddress = await trustRegistry.getAddress();
  const adminAddress = (await hre.ethers.getSigners())[0].address;
  const artifact = await hre.artifacts.readArtifact("TrustRegistry");

  console.log(`TrustRegistry deployed to: ${deployedAddress}`);
  console.log("Owner/Admin address:", adminAddress);

  // Auto-write the deployed address to the frontend contracts config
  const contractsFilePath = path.join(
    __dirname,
    "../../frontend/src/app/lib/contracts.ts"
  );

  const contractsContent = `// AUTO-GENERATED by deploy.cjs — do not edit manually
// Re-run 'npx hardhat run scripts/deploy.cjs --network localhost' to update

export const TRUST_REGISTRY_ADDRESS = '${deployedAddress}' as \`0x\${string}\`;

export const ADMIN_ADDRESS = '${adminAddress}' as \`0x\${string}\`;

export const TRUST_REGISTRY_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;

export const ROLE = {
  NONE: 0,
  CITIZEN: 1,
  ISSUER: 2,
  VERIFIER: 3,
} as const;

export type ContractRole = typeof ROLE[keyof typeof ROLE];
`;

  fs.writeFileSync(contractsFilePath, contractsContent, "utf8");
  console.log(`\n✅ contracts.ts updated at: ${contractsFilePath}`);
  console.log(`   Contract Address: ${deployedAddress}`);
  console.log(`   Admin Address:    ${adminAddress}`);
  console.log("\n🚀 Ready! Start the frontend with: cd ../frontend && npm run dev");
}

// Run the script
main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
